apiVersion: v1
kind: ConfigMap
metadata:
  name: license-server-config
  namespace: license-system
  labels:
    app: license-server
data:
  config.yml: |
    # Server Configuration
    server:
      port: 8080
      host: "0.0.0.0"
      read_timeout: "30s"
      write_timeout: "30s"
      idle_timeout: "120s"
      graceful_shutdown_timeout: "30s"

    # Database Configuration
    database:
      mysql:
        host: "license-mysql"
        port: 3306
        user: "license_user"
        database: "license_db"
        max_open_conns: 25
        max_idle_conns: 5
        conn_max_lifetime: "5m"
        conn_max_idle_time: "1m"
      
      redis:
        host: "license-redis"
        port: 6379
        database: 0
        pool_size: 10
        min_idle_conns: 5

    # Security Configuration
    security:
      jwt:
        expiration: "24h"
        refresh_expiration: "168h"  # 7 days
      
      rate_limiting:
        enabled: true
        requests_per_minute: 100
        burst: 20
      
      encryption:
        algorithm: "AES-256-GCM"

    # Monitoring Configuration
    monitoring:
      prometheus:
        enabled: true
        port: 9090
        path: "/metrics"
      
      logging:
        level: "info"  # debug, info, warn, error
        format: "json"  # json, text
        output: "stdout"  # stdout, file, both

    # Feature Flags
    features:
      caching: true
      audit_logging: true
      metrics_collection: true
      health_checks: true