apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: license-system
  labels:
    app: license-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: Service
metadata:
  name: license-mysql
  namespace: license-system
  labels:
    app: license-server
    component: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: license-server
    component: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-mysql
  namespace: license-system
  labels:
    app: license-server
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license-server
      component: mysql
  template:
    metadata:
      labels:
        app: license-server
        component: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: license-server-secrets
              key: db-password
        - name: MYSQL_DATABASE
          value: "license_db"
        - name: MYSQL_USER
          value: "license_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: license-server-secrets
              key: db-password
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-init
        configMap:
          name: mysql-init-script
      restartPolicy: Always